name: cipipeline

on: 
  push: 
    branches: [ "main" ]
  workflow_dispatch: 

jobs:
  ci-job:
    runs-on: ubuntu-latest
    steps:
      
      - name: copy code to github
        uses: actions/checkout@v4
      - name: verify files
        run: |
          echo "list the files"
          ls
      - name: validate if html.index exist or not
        run: |
          if [ ! -f index.html ]; then echo "index.html not exist"
            exit 1
          fi
      - name: uploading index.html to artifacts
        uses: actions/upload-artifact@v4
        with:
          name: website-file
          path: |
            index.html

deployment:
  needs: ci-job
  runs-on: ubuntu-latest
  
  steps:
    - name: download artifacts
      uses: actions/download-artifact@v4
      with: 
        name: website-file

    - name: configure aws credentials
      
      uses: aws-actions/configure-aws-credentials@v4
      with:
         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
         aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
         aws-region: ap-south-1

    - name: deploy files to s3 bucket
      run: aws s3 sync . s3://amazon-s3-bucket12354
      
    

          
          
