name: cipipeline
on: 
  push: 
  branches["main"]
  pull:
  branches["main"]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    uses: actions/checkout@v4

    steps:
     -name: print hello
      runs: echo"hello world"
    
