name: ci pipeline

on: 
  push: 
    branches: [ "main" ]
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses:  actions/checkout@v4

      - name: print current directory
        run: pwd

      - name: list files
        run: ls -la

      - name: print current date
        run: date
    
