name: cipipeline

on: 
  push: 
    branches: [ "main" ]
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      
      - name: copy code to github
        uses: actions/checkout@v4
      - name: verify files
        run: |
          echo "list the files"
          ls
      - name: validate if html.index exist or not
        run: |
          if [ ! -f index.html ]; then echo "index.html not exist"
            exit 1
          fi
          
          
