name: ci pipeline

on: 
  push: 
    branches: [ "main" ]
  workflow_dispatch: 

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: checkout code
        uses:  actions/checkout@v4

      - name: list the files
        run: echo "list the files" ls
              
      - name: check whether the index.html exist or not
        run: if [ ! -f index.html ]; echo then "index.html does not exist"
             exit1
             fi
      - name: upload artifacts
        uses: action/upload-artifact@v4
        
